/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-dvbs2acm
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_DVBS2ACM_API_H
#define INCLUDED_DVBS2ACM_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_dvbs2acm_EXPORTS
#define DVBS2ACM_API __GR_ATTR_EXPORT
#else
#define DVBS2ACM_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_DVBS2ACM_API_H */
