/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(bch_decoder_bb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(78f922182737415261a3a7c63455a770)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dvbs2acm/bch_decoder_bb.h>
// pydoc.h is automatically generated in the build directory
#include <bch_decoder_bb_pydoc.h>

void bind_bch_decoder_bb(py::module& m)
{

    using bch_decoder_bb    = gr::dvbs2acm::bch_decoder_bb;


    py::class_<bch_decoder_bb, gr::block, gr::basic_block,
        std::shared_ptr<bch_decoder_bb>>(m, "bch_decoder_bb", D(bch_decoder_bb))

        .def(py::init(&bch_decoder_bb::make),
           D(bch_decoder_bb,make)
        )
        



        ;




}








