/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(deinterleaver_bb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(a9aa6d5da6782de7397c892562cb5055)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dvbs2acm/deinterleaver_bb.h>
// pydoc.h is automatically generated in the build directory
#include <deinterleaver_bb_pydoc.h>

void bind_deinterleaver_bb(py::module& m)
{

    using deinterleaver_bb    = ::gr::dvbs2acm::deinterleaver_bb;


    py::class_<deinterleaver_bb, gr::tagged_stream_block, gr::block, gr::basic_block,
        std::shared_ptr<deinterleaver_bb>>(m, "deinterleaver_bb", D(deinterleaver_bb))

        .def(py::init(&deinterleaver_bb::make),
           D(deinterleaver_bb,make)
        )
        



        ;




}








