/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(demodulator_cb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(853feaea802fcba9d4fe8989308f3aa4)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dvbs2acm/demodulator_cb.h>
// pydoc.h is automatically generated in the build directory
#include <demodulator_cb_pydoc.h>

void bind_demodulator_cb(py::module& m)
{

    using demodulator_cb    = ::gr::dvbs2acm::demodulator_cb;


    py::class_<demodulator_cb, gr::block, gr::basic_block,
        std::shared_ptr<demodulator_cb>>(m, "demodulator_cb", D(demodulator_cb))

        .def(py::init(&demodulator_cb::make),
           py::arg("precision"),
           D(demodulator_cb,make)
        )
        




        
        .def("set_precision",&demodulator_cb::set_precision,       
            py::arg("precision"),
            D(demodulator_cb,set_precision)
        )

        ;




}








