/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(dvbs2_config.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(8524f6ed358ba9a5b092e40235ea2ca3)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dvbs2acm/dvbs2_config.h>
// pydoc.h is automatically generated in the build directory
// #include <dvbs2acm_config_pydoc.h>

void bind_dvbs2_config(py::module& m)
{
    py::enum_<::gr::dvbs2acm::dvbs2_framesize_t>(m, "dvbs2_framesize_t")
        .value("FECFRAME_NORMAL", ::gr::dvbs2acm::FECFRAME_NORMAL) // 0
        .value("FECFRAME_SHORT", ::gr::dvbs2acm::FECFRAME_SHORT)   // 1
        .value("FECFRAME_MEDIUM", ::gr::dvbs2acm::FECFRAME_MEDIUM) // 2
        .export_values();
    py::enum_<::gr::dvbs2acm::dvbs2_code_rate_t>(m, "dvbs2_code_rate_t")
        .value("C1_4", ::gr::dvbs2acm::C1_4)                         // 0
        .value("C1_3", ::gr::dvbs2acm::C1_3)                         // 1
        .value("C2_5", ::gr::dvbs2acm::C2_5)                         // 2
        .value("C1_2", ::gr::dvbs2acm::C1_2)                         // 3
        .value("C3_5", ::gr::dvbs2acm::C3_5)                         // 4
        .value("C2_3", ::gr::dvbs2acm::C2_3)                         // 5
        .value("C3_4", ::gr::dvbs2acm::C3_4)                         // 6
        .value("C4_5", ::gr::dvbs2acm::C4_5)                         // 7
        .value("C5_6", ::gr::dvbs2acm::C5_6)                         // 8
        .value("C8_9", ::gr::dvbs2acm::C8_9)                         // 9
        .value("C9_10", ::gr::dvbs2acm::C9_10)                       // 10
        .value("C13_45", ::gr::dvbs2acm::C13_45)                     // 11
        .value("C9_20", ::gr::dvbs2acm::C9_20)                       // 12
        .value("C90_180", ::gr::dvbs2acm::C90_180)                   // 13
        .value("C96_180", ::gr::dvbs2acm::C96_180)                   // 14
        .value("C11_20", ::gr::dvbs2acm::C11_20)                     // 15
        .value("C100_180", ::gr::dvbs2acm::C100_180)                 // 16
        .value("C104_180", ::gr::dvbs2acm::C104_180)                 // 17
        .value("C26_45", ::gr::dvbs2acm::C26_45)                     // 18
        .value("C18_30", ::gr::dvbs2acm::C18_30)                     // 19
        .value("C28_45", ::gr::dvbs2acm::C28_45)                     // 20
        .value("C23_36", ::gr::dvbs2acm::C23_36)                     // 21
        .value("C116_180", ::gr::dvbs2acm::C116_180)                 // 22
        .value("C20_30", ::gr::dvbs2acm::C20_30)                     // 23
        .value("C124_180", ::gr::dvbs2acm::C124_180)                 // 24
        .value("C25_36", ::gr::dvbs2acm::C25_36)                     // 25
        .value("C128_180", ::gr::dvbs2acm::C128_180)                 // 26
        .value("C13_18", ::gr::dvbs2acm::C13_18)                     // 27
        .value("C132_180", ::gr::dvbs2acm::C132_180)                 // 28
        .value("C22_30", ::gr::dvbs2acm::C22_30)                     // 29
        .value("C135_180", ::gr::dvbs2acm::C135_180)                 // 30
        .value("C140_180", ::gr::dvbs2acm::C140_180)                 // 31
        .value("C7_9", ::gr::dvbs2acm::C7_9)                         // 32
        .value("C154_180", ::gr::dvbs2acm::C154_180)                 // 33
        .value("C11_45", ::gr::dvbs2acm::C11_45)                     // 34
        .value("C4_15", ::gr::dvbs2acm::C4_15)                       // 35
        .value("C14_45", ::gr::dvbs2acm::C14_45)                     // 36
        .value("C7_15", ::gr::dvbs2acm::C7_15)                       // 37
        .value("C8_15", ::gr::dvbs2acm::C8_15)                       // 38
        .value("C32_45", ::gr::dvbs2acm::C32_45)                     // 39
        .value("C2_9_VLSNR", ::gr::dvbs2acm::C2_9_VLSNR)             // 40
        .value("C1_5_MEDIUM", ::gr::dvbs2acm::C1_5_MEDIUM)           // 41
        .value("C11_45_MEDIUM", ::gr::dvbs2acm::C11_45_MEDIUM)       // 42
        .value("C1_3_MEDIUM", ::gr::dvbs2acm::C1_3_MEDIUM)           // 43
        .value("C1_5_VLSNR_SF2", ::gr::dvbs2acm::C1_5_VLSNR_SF2)     // 44
        .value("C11_45_VLSNR_SF2", ::gr::dvbs2acm::C11_45_VLSNR_SF2) // 45
        .value("C1_5_VLSNR", ::gr::dvbs2acm::C1_5_VLSNR)             // 46
        .value("C4_15_VLSNR", ::gr::dvbs2acm::C4_15_VLSNR)           // 47
        .value("C1_3_VLSNR", ::gr::dvbs2acm::C1_3_VLSNR)             // 48
        .value("C_OTHER", ::gr::dvbs2acm::C_OTHER)                   // 49
        .export_values();
    py::enum_<::gr::dvbs2acm::dvbs2_rolloff_factor_t>(m, "dvbs2_rolloff_factor_t")
        .value("RO_0_35", ::gr::dvbs2acm::RO_0_35)         // 0
        .value("RO_0_25", ::gr::dvbs2acm::RO_0_25)         // 1
        .value("RO_0_20", ::gr::dvbs2acm::RO_0_20)         // 2
        .value("RO_RESERVED", ::gr::dvbs2acm::RO_RESERVED) // 3
        .value("RO_0_15", ::gr::dvbs2acm::RO_0_15)         // 4
        .value("RO_0_10", ::gr::dvbs2acm::RO_0_10)         // 5
        .value("RO_0_05", ::gr::dvbs2acm::RO_0_05)         // 6
        .export_values();
    py::enum_<::gr::dvbs2acm::dvbs2_constellation_t>(m, "dvbs2_constellation_t")
        .value("MOD_QPSK", ::gr::dvbs2acm::MOD_QPSK)                 // 0
        .value("MOD_8PSK", ::gr::dvbs2acm::MOD_8PSK)                 // 1
        .value("MOD_8APSK", ::gr::dvbs2acm::MOD_8APSK)               // 2
        .value("MOD_16APSK", ::gr::dvbs2acm::MOD_16APSK)             // 3
        .value("MOD_8_8APSK", ::gr::dvbs2acm::MOD_8_8APSK)           // 4
        .value("MOD_32APSK", ::gr::dvbs2acm::MOD_32APSK)             // 5
        .value("MOD_4_12_16APSK", ::gr::dvbs2acm::MOD_4_12_16APSK)   // 6
        .value("MOD_4_8_4_16APSK", ::gr::dvbs2acm::MOD_4_8_4_16APSK) // 7
        .value("MOD_BPSK", ::gr::dvbs2acm::MOD_BPSK)                 // 8
        .value("MOD_BPSK_SF2", ::gr::dvbs2acm::MOD_BPSK_SF2)         // 9
        .value("MOD_OTHER", ::gr::dvbs2acm::MOD_OTHER)               // 10
        .export_values();
}
