/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ldpc_encoder_bb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(94e8df2443557729cc2d4e701701e67e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dvbs2acm/ldpc_encoder_bb.h>
// pydoc.h is automatically generated in the build directory
#include <ldpc_encoder_bb_pydoc.h>

void bind_ldpc_encoder_bb(py::module& m)
{

    using ldpc_encoder_bb = ::gr::dvbs2acm::ldpc_encoder_bb;


    py::class_<ldpc_encoder_bb,
               gr::tagged_stream_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<ldpc_encoder_bb>>(m, "ldpc_encoder_bb", D(ldpc_encoder_bb))

        .def(py::init(&ldpc_encoder_bb::make), D(ldpc_encoder_bb, make))


        ;
}
